# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76f2dd6397076063a3fac55eb2362c03831a4c5fad7dbb5521e02b1f60947a95f237220348e1200a84863aff03359940e2c5c6143679f1457243997e51cbd34c

test:
  secret_key_base: 86e880212e94b419af1c98052fb1b5ad8b244e0b7134a08daf067c4ef1b4addd12a0f1e6c0f3c86c49fb5fc1f1a729923e188e78b839391157b6ef7f2eb74f96

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
